# Generated by Django 5.0.6 on 2024-05-23 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ynab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="depense",
            name="montant",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="depense",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
    ]
