# Generated by Django 5.0.6 on 2024-05-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ynab", "0002_alter_depense_date_alter_depense_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ynab.user"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ynab.user"
            ),
        ),
    ]
