# Generated by Django 5.0.6 on 2024-05-23 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ynab", "0003_alter_categorie_user_alter_depense_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="depense",
            old_name="Categorie",
            new_name="categorie",
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ynab.categorie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ynab.user"
                    ),
                ),
            ],
        ),
    ]
